# -*- coding: utf-8 -*-
"""Book_recommdation_using_book_ranking.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1loLQ97yyyRmuLAqEL-KycThqEp1v6NBc
"""

import pandas as pd 
import numpy as np

data = pd.read_csv('listing.csv', encoding = 'latin-1')
books= pd.read_csv('books.csv', encoding = 'latin-1')

data.head()

books.head()

rating_count = pd.DataFrame(books, columns=['book_id','no_of_ratings'])
rating_count.sort_values('no_of_ratings', ascending=False).drop_duplicates().head(10)

most_rated_books = pd.DataFrame([4755, 2409, 2194, 4696, 1616], index=np.arange(5), columns=['book_id'])
detail = pd.merge(most_rated_books, data, on='book_id')
detail

most_rated_book = pd.DataFrame(books, columns=['book_id', 'user_id', 'avg_rating', 'no_of_ratings'])
most_rated_book.max()

most_rated_book.describe()

data['author'].describe()

